#!/bin/python3

import sys

def divisibleSumPairs(n, k, ar):
    result = 0
    for i in range(n):
        for j in range(i+1,n):
            #print ((i,j),(ar[i],ar[j]))
            if (ar[i]+ar[j])%k==0:
                #print ('check')
                result+=1
    return result
n, k = input().strip().split(' ')
n, k = [int(n), int(k)]
ar = list(map(int, input().strip().split(' ')))
result = divisibleSumPairs(n, k, ar)
print(result)
